---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, flexgroup, ontap s3, s3 configuration, svm dr, svm disaster recovery, disaster recovery, storage vm dr 
summary: Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con esta versión del producto o cuya interoperabilidad con esta no es óptima. Revise estas limitaciones detenidamente. 
---
= Limitaciones conocidas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con esta versión del producto o cuya interoperabilidad con esta no es óptima. Revise estas limitaciones detenidamente.

Estas limitaciones son específicas de la gestión de Cloud Volumes ONTAP en BlueXP (anteriormente Cloud Manager). Para ver las limitaciones con el propio software de Cloud Volumes ONTAP, https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limitations.html["Vaya a las notas de la versión de Cloud Volumes ONTAP"^]



== BlueXP no es compatible con volúmenes de FlexGroup

Aunque Cloud Volumes ONTAP es compatible con volúmenes de FlexGroup, BlueXP no. Si crea un volumen de FlexGroup desde System Manager o desde la CLI, debe configurar el modo de gestión de capacidad de BlueXP en Manual. El modo automático puede no funcionar correctamente con volúmenes de FlexGroup.



== BlueXP no es compatible con S3 con Cloud Volumes ONTAP

Aunque Cloud Volumes ONTAP admite S3 como opción para el almacenamiento de escalado horizontal de algunos proveedores de cloud, BlueXP no proporciona ninguna funcionalidad de gestión para esta función. Usar la CLI es la práctica recomendada para configurar el acceso del cliente S3 desde Cloud Volumes ONTAP. Para obtener más información, consulte http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-s3-cg/home.html["Guía completa de configuración de S3"^].

link:concept-client-protocols.html["Obtenga más información sobre la compatibilidad de Cloud Volumes ONTAP con S3 y otros protocolos de cliente"].



== BlueXP no admite recuperación ante desastres para equipos virtuales de almacenamiento

BlueXP no ofrece ninguna compatibilidad de configuración o orquestación para la recuperación ante desastres de equipos virtuales de almacenamiento. Se debe usar System Manager o la CLI.

* https://library.netapp.com/ecm/ecm_get_file/ECMLP2839856["Guía exprés de preparación para la recuperación de desastres de SVM"^]
* https://library.netapp.com/ecm/ecm_get_file/ECMLP2839857["Guía exprés de recuperación ante desastres de SVM"^]

