---
sidebar: sidebar 
permalink: task-encrypting-volumes.html 
keywords: encrypt, encryption, data, volumes, netapp volume encryption, volume encryption, nve, key managers, kmip, key management servers, license, ssl certificates, nae, netapp aggregate encryption 
summary: 'Cloud Volumes ONTAP es compatible tanto con el cifrado de volúmenes de NetApp (NVE) como con el cifrado de agregados de NetApp (NAE) con un gestor de claves externo. NVE y NAE se habilitan de forma predeterminada si configura un gestor de claves externo.' 
---
= Cifrar volúmenes con soluciones de cifrado de NetApp
:toc: macro
:hardbreaks:
:allow-uri-read: 
:toc: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Cloud Volumes ONTAP admite el cifrado de volúmenes de NetApp (NVE) y el cifrado de agregados de NetApp (NAE). NVE y NAE son soluciones basadas en software que permiten el cifrado de volúmenes para datos en reposo conforme a la normativa FIPS 140-2. link:concept-security.html["Obtenga más información sobre estas soluciones de cifrado"].

Tanto NVE como NAE son compatibles con un gestor de claves externo.

ifdef::azure[]

endif::azure[]

ifdef::gcp[]

endif::gcp[]

Los nuevos agregados tendrán NAE habilitado de forma predeterminada después de configurar un gestor de claves externo. Los volúmenes nuevos que no forman parte de un agregado de NAE tendrán el valor de NVE habilitado de forma predeterminada (por ejemplo, si tiene agregados existentes que se crearon antes de configurar un gestor de claves externo).

Cloud Volumes ONTAP no admite la gestión de claves incorporada.

.Lo que necesitará
Su sistema Cloud Volumes ONTAP debe registrarse con el soporte de NetApp. Una licencia de cifrado de volúmenes de NetApp se instala automáticamente en cada sistema Cloud Volumes ONTAP registrado en el soporte de NetApp.

* https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-adding-nss-accounts.html["Adición de cuentas del sitio de soporte de NetApp a BlueXP"^]
* link:task-registering.html["Registro de sistemas de pago por uso"]



NOTE: BlueXP no instala la licencia NVE en sistemas que residen en la región China.

.Pasos
. Revise la lista de administradores de claves compatibles en la http://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^].
+

TIP: Busque la solución *Key Managers*.

. link:task-connecting-to-otc.html["Conéctese a la CLI de Cloud Volumes ONTAP"^].
. Configure la gestión de claves externas.
+
ifdef::aws[]

+
** AWS: https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-external-key-management-overview-concept.html["Para obtener instrucciones, vaya a la documentación de ONTAP"^]




endif::aws[]

ifdef::azure[]

* Azure: link:task-azure-key-vault.html["Azure Key Vault (AKV)"]


endif::azure[]

ifdef::gcp[]

* Google Cloud: link:task-google-key-manager.html["Servicio de gestión de claves de Google Cloud"]


endif::gcp[]
